AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashCreatePaymentInitModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashCreatePaymentInitModel
    {
        public string currency { get; set; }
        public string amount { get; set; }
        public string intent { get; set; }
        public string invoiceNumber { get; set; }

    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashCreatePaymentReturnModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashCreatePaymentReturnModel
    {
        public string paymentID { get; set; }
        public string createTime { get; set; }
        public string orgLogo { get; set; }
        public string orgName { get; set; }
        public string transactionStatus { get; set; }
        public string amount  { get; set; }
        public string currency { get; set; }

        public string intent { get; set; }
        public string merchantInvoiceNumber { get; set; }
        public string errorCode { get; set; }
        public string errorMessage { get; set; }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashCredentials.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashCredentials
    {
        public string UserName { get; set; }

        public string Password { get; set; }

        public string AppKey { get; set; }

        public string AppSecret { get; set; }

        public string Token { get; set; }

        public string RefreshToken { get; set; }

        public DateTime? CreatedOn { get; set; }

        public decimal? ValiditySeconds { get; set; }

    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashExecutePaymentInitModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashExecutePaymentInitModel
    {
        public string paymentID { get; set; }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashExecutePaymentReturnModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashExecutePaymentReturnModel
    {
        public string paymentID { get; set; }
        public string createTime { get; set; }
        public string updateTime { get; set; }
        public string trxID { get; set; }
        public string transactionStatus { get; set; }
        public string amount { get; set; }
        public string currency { get; set; }
        public string intent { get; set; }
        public string merchantInvoiceNumber { get; set; }
        public string customerMsisdn { get; set; }
        public string errorCode { get; set; }
        public string errorMessage { get; set; }

    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashGrantTokenModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashGrantTokenModel
    {
        public string id_token { get; set; }
        public string token_type { get; set; }
        public int ? expires_in { get; set; }
        public string refresh_token { get; set; }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashQueryPaymentReturnModel.cs
namespace ClubWebsite.Models.Payment
{
    public class BkashQueryPaymentReturnModel
    {
        public string paymentID { get; set; }
        public string createTime { get; set; }
        public string updateTime { get; set; }
        public string trxID { get; set; }
        public string transactionStatus { get; set; }
        public string amount { get; set; }
        public string currency { get; set; }
        public string intent { get; set; }
        public string merchantInvoiceNumber { get; set; }
        public string refundAmount { get; set; }
        public string customerMsisdn { get; set; }
        public string errorCode { get; set; }
        public string errorMessage { get; set; }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Models/Payment/BkashSearchTransactionReturnModel.cs
using AutoMapper.Execution;
using Microsoft.SqlServer.Server;
using Newtonsoft.Json.Linq;
using System.Diagnostics.Metrics;
using System.Drawing;
using System.Transactions;
using System;
using System.Net.Http;
using Azure.Core;
using System.Data.Common;
using System.Security.Cryptography.Xml;

namespace ClubWebsite.Models.Payment
{
    public class BkashSearchTransactionReturnModel
    {
        public string amount { get; set; }
        public string completedTime { get; set; }
        public string currency { get; set; }
        public string customerMsisdn { get; set; }
        public string initiationTime { get; set; }
        public string organizationShortCode { get; set; }
        public string transactionReference { get; set; }
        public string transactionStatus { get; set; }
        public string transactionType { get; set; }
        public string trxID { get; set; }
        public string errorCode { get; set; }
        public string errorMessage { get; set; }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Controllers/JoinController.cs
using ClubWebsite.Models.Common;
using ClubWebsite.Models;
using ClubWebsite.Service.Join;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.RegularExpressions;
using System.Diagnostics.Metrics;
using System.Net;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using System;
using AutoMapper;
using ClubWebsite.Mapper;
using ClubWebsite.Infrastructure;
using RestSharp;
using AutoMapper.Execution;
using ClubWebsite.Models.Join;
using ClubWebsite.Service.Sms;
using ClubWebsite.Models.Sms;
using Microsoft.Extensions.Configuration;
using ClubWebsite.Service.Payment;
using ClubWebsite.Models.Payment;
using ClubWebsite.Service.Email;
using ClubWebsite.Models.Email;
using ClubWebsite.Service.Template;
using Org.BouncyCastle.Asn1.X509;
using static System.Net.Mime.MediaTypeNames;
using System.Drawing;
using System.Reflection;
using System.Text.Json.Serialization;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace ClubWebsite.Controllers
{
    public class JoinController : Controller
    {
        private readonly IJoinService _joinService;
        public JoinController(IJoinService joinService)
        {
            _joinService = joinService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Departments = await _joinService.GetDepartmentList();
            ViewBag.Semesters = await _joinService.GetSemesterList();
            ViewBag.IsExistingReg = false;
            ViewBag.Fee = "105";
            try
            {
                var cookie = HttpContext.User.FindFirstValue("Join-AUSTPIC-Member-Token");
                if (cookie != null && await _joinService.VerifyTokenForMember(cookie))
                {
                    ViewBag.IsExistingReg = true;
                } 
            }
            catch(Exception e)
            {
            }
            return View();
        }
        public IActionResult Success()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> CheckMemberInformationNew(MemberViewModel member)
        {
            var req = HttpContext.Request;
            JsonResult json =  await _joinService.CheckMemberInformationNew(member);
            if (json.Value.ToString().Contains("status = True"))
            {
                /*CookieOptions option = new CookieOptions();
                option.Path = "/";
                option.Expires = DateTime.Now.AddDays(1);
                option.Secure = true;
                option.HttpOnly = true;*/
                string Token = await _joinService.GenerateTokenForMember();
                //HttpContext.Response.Cookies.Append("Join-AUSTPIC-Web-App-Member", Token, option);
                var claims = new List<Claim>
                {
                    new Claim("Join-AUSTPIC-Member-Token", Token)
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity));
                await _joinService.InsertNewMemberTemp(member, Token);
            }
            return json;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Controllers/PaymentController.cs
using AutoMapper;
using ClubWebsite.Service.Payment;
using Microsoft.AspNetCore.Mvc;
using ClubWebsite.Models.Payment;
using RestSharp;
using Newtonsoft.Json.Linq;
using System.Text.Json;
using System.Runtime.CompilerServices;
using Azure;
using ClubWebsite.Models.Common;
using ClubWebsite.Service.Join;
using AutoMapper.Execution;
using ClubWebsite.Models.Join;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using ClubWebsite.Models;
using System.Diagnostics;

namespace ClubWebsite.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly IPaymentService _paymentService;
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;
        private readonly IJoinService _joinService;

        public PaymentController(IPaymentService paymentService, IMapper mapper, IConfiguration configuration,IJoinService joinService)
        {
            _paymentService = paymentService;
            _mapper = mapper;
            _configuration = configuration;
            _joinService = joinService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                ViewBag.Fee = _configuration.GetSection("Payment")["GetGMRecruitmentFee"];
                var cookie = HttpContext.User.FindFirstValue("Join-AUSTPIC-Member-Token");
                List<MemberToken> tokens = await _joinService.GetTokenForMember(cookie);
                if (tokens.Count > 0)
                {
                    ViewBag.Name = tokens[0].Name;
                    ViewBag.Email = tokens[0].Email;
                    ViewBag.MobileNo = tokens[0].MobileNo;
                }
                else
                {
                    ViewBag.Name = "Not Found";
                    ViewBag.Email = "Not Found";
                    ViewBag.MobileNo = "Not Found";
                }
            }
            catch(Exception e)
            {
                ViewBag.Name = "Not Found";
                ViewBag.Email = "Not Found";
                ViewBag.MobileNo = "Not Found";
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<BkashCreatePaymentReturnModel> CreatePaymentInit()
        {
            try
            {
                var cookie = HttpContext.User.FindFirstValue("Join-AUSTPIC-Member-Token");
                if (cookie == null || !await _joinService.VerifyTokenForMember(cookie))
                {
                    BkashCreatePaymentReturnModel model = new BkashCreatePaymentReturnModel();
                    model.errorMessage = "UnAuthorized";
                    return model;
                }
                BkashCreatePaymentInitModel createModel = new BkashCreatePaymentInitModel();
                createModel.amount = _configuration.GetSection("Payment")["GetGMRecruitmentFee"];
                createModel.intent = "sale";
                createModel.invoiceNumber = await _paymentService.GenerateInvoiceNumber();
                createModel.currency = "BDT";
                return await _paymentService.CreatePayment(createModel);
            }
            catch(Exception e)
            {
                return new BkashCreatePaymentReturnModel();
            }
        }
        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<BkashExecutePaymentReturnModel> ExecutePaymentInit(string PaymentID)
        {
            try
            {
                var cookie = HttpContext.User.FindFirstValue("Join-AUSTPIC-Member-Token");
                if (cookie == null || !await _joinService.VerifyTokenForMember(cookie))
                {
                    BkashExecutePaymentReturnModel model = new BkashExecutePaymentReturnModel();
                    model.errorMessage = "UnAuthorized";
                    return model;
                }
                BkashExecutePaymentInitModel executionCreateModel = new BkashExecutePaymentInitModel();
                executionCreateModel.paymentID = PaymentID;

                BkashExecutePaymentReturnModel executionReturnModel = await _paymentService.ExecutePayment(executionCreateModel);
                if (executionReturnModel != null && executionReturnModel.paymentID != null)
                {
                    try
                    {
                        //BkashSearchTransactionReturnModel returnModel = await _paymentService.SearchTransaction(executionReturnModel.trxID);
                        //await _paymentService.InsertTransactionDB(returnModel);
                        await _joinService.InsertNewMemberFromTemp(executionReturnModel, cookie);
                    }
                    catch (Exception e)
                    {

                    }
                    await HttpContext.SignOutAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme);
                }
                return executionReturnModel;
            }
            catch(Exception e)
            {
                return new BkashExecutePaymentReturnModel();
            }
        }
        [Authorize]
        private async Task<BkashQueryPaymentReturnModel> QueryPaymentInit(string paymentID)
        {
            return await _paymentService.QueryPayment(paymentID);
        }
        [Authorize]
        private async Task<BkashSearchTransactionReturnModel> SearchTransactionInit(string trxId)
        {
            return await _paymentService.SearchTransaction(trxId);
        }
    }
}

AustPIC_official-main/join-austpic-main/WebApplication1/Views/Payment/Index.cshtml
@{
    ViewData["Title"] = "Payment";
    Layout = "~/Views/Shared/_PaymentLayout.cshtml";
}
<header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
        <a href="join" class="logo d-flex align-items-center">
            <img src="~/img/common/club_logo_large.png" alt="">
            <span>AUSTPIC</span>
        </a>
    </div>
</header>
<br>
<br>
<div style="background-color: #e6ebf4 !important;">

    <div class="payment container mt-5 mb-5 d-flex justify-content-center">
        <div class="card p-5"> 
            <div>
                    <h4 class="heading" style="align-content:center;">Payment Procedure</h4>
                </div> 
            <div class="pricing p-3 rounded mt-4 d-flex justify-content-between"> 
                <div class="images d-flex flex-row align-items-center"> 
                    <div class="d-flex flex-column ml-4"> 
                        <span class="business">Permanent</span>
                            <span class="business">Membership</span>
                        </div> 
                </div> <!--pricing table--> 
                <div class="d-flex flex-row align-items-center"> 
                    <sup class="dollar font-weight-bold">BDT</sup> 
                    <span class="amount ml-1 mr-1">@ViewBag.Fee</span>

                </div> <!-- /pricing table--> 
            </div> 
            <span class="detail mt-5">Your Details</span> 
            <div class="mt-2 d-flex justify-content-between align-items-center"> 
                <div class="d-flex flex-row align-items-center textlabel"> 
                    <p>Name:</p>
                </div>
                    <div class="mt-2">
                    <input type="text" value=@(String.IsNullOrEmpty(ViewBag.Name) ? "Not Found" : ViewBag.Name) class="form-control textbox" readonly>
                    </div> 
            </div> 
            <div class="mt-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center textlabel">
                    <p>Email:</p>
                </div>
                <div>
                    <input type="text" value=@(String.IsNullOrEmpty(ViewBag.Email) ? "" : ViewBag.Email) class="form-control textbox" readonly>
                </div>
            </div>
            <div class="mt-2 d-flex justify-content-between align-items-center">
                <div class="d-flex flex-row align-items-center textlabel">
                    <p>Mobile No:</p>
                </div>
                <div>
                    <input type="text" value=@(String.IsNullOrEmpty(ViewBag.MobileNo) ? "" : ViewBag.MobileNo) class="form-control textbox" readonly>
                </div>
            </div>
            <span class="detail mt-5">Select Payment Method</span>
            <div class="mt-3">
                <button onclick="clickPayButton()" style="box-shadow: 0 0 35px 0 rgb(154 161 171);">
                    <img class="bkash-image" src="~/img/payment/bkash.svg" alt="Bkash">
                    @Html.AntiForgeryToken()
                </button>
            </div> 
        </div> 
    </div>
</div>
<button style="display:none;" id="bKash_button"></button>
@section Scripts
{
<script>
    var ClubWebsiteUrls = {
        CHECK_NEW_MEMBER_INFO: '@Url.Action("CheckMemberInformationNew", "Join")',
        MERCHANT_BACKEND_CREATE_API_CALLER_URL: '@Url.Action("CreatePaymentInit", "Payment")',
        MERCHANT_BACKEND_EXECUTE_API_CALLER_URL: '@Url.Action("ExecutePaymentInit", "Payment")',
        SUCCESSFUL_PAYMENT: '@Url.Action("Success", "Join")'
    };
    var PAYMENT_FEE = '@ViewBag.Fee';
</script>
<script src="~/bundles/payment-js-bundle.min.js" ></script>
<script>
    document.addEventListener("contextmenu", (e) => {
        e.preventDefault();
    }, false);
</script>
}

AustPIC_official-main/join-austpic-main/WebApplication1/Views/Payment/Success.cshtml
@{
    ViewData["Title"] = "Success";
    Layout = "~/Views/Shared/_PaymentLayout.cshtml";
}
<p>Your Payment is Successful</p>

@section Scripts
{
    <script>
        var success = '@Url.Action("Index", "Join")';
    </script>
    <script>
        $(document).ready(function () {
            bootbox.alert({
                title: "Successful",
                message: "Congratulations!Your payment is successful",
                callback: function () {
                    window.location.href = success;
                }
            });
        });
    </script>
}