AustPIC_official-main/AustPICWeb/Controllers/AboutController.cs
using AustPICWeb.Repositories.CssVariable;
using Microsoft.AspNetCore.Mvc;

namespace AustPICWeb.Controllers
{
    public class AboutController : Controller
    {
        private readonly ICssRepository _cssRepository;

        public AboutController(ICssRepository cssRepository)
        {
            _cssRepository = cssRepository;
        }

        public async Task<IActionResult> Index()
        {
            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;
            return View();
        }
    }
}

AustPIC_official-main/AustPICWeb/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using AustPIC.db.DbOperations;
using AustPIC.Models;
using Microsoft.AspNetCore.Authorization;
using AustPIC.Models.ViewModels;
using System.Net.Mail;
using System.Net;

namespace AustPICWeb.Controllers
{

    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        CommitteeRepository CmtRepository = null;
        EventRepository EvntRepository = null;
        //ContactRepository contactRepository = null;
        CssRepository CssRepository = null;
        private IConfiguration Configuration;

        public AdminController(IConfiguration _configuration)
        {
            CmtRepository = new CommitteeRepository();
            EvntRepository = new EventRepository();
            //contactRepository = new ContactRepository();
            CssRepository = new CssRepository();
            Configuration = _configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddCommittee()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCommittee(CommitteeModel model)
        {
            if (ModelState.IsValid)
            {
                int id = CmtRepository.AddCommittee(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.success = "Data Added";
                }
            }
            return View();
        }

        public IActionResult GetAllCommittee()
        {
            var result = CmtRepository.GetAllCommittee();
            return View(result);
        }

        public IActionResult CommitteeDetails(int id)
        {
            var committee = CmtRepository.GetCommittee(id);
            return View(committee);
        }

        [HttpGet]
        public IActionResult EditCommittee(int id)
        {
            var committee = CmtRepository.GetCommittee(id);
            return View(committee);
        }

        [HttpPost]
        public IActionResult EditCommittee(CommitteeModel model)
        {
            if (ModelState.IsValid)
            {
                CmtRepository.UpdateCommittee(model.CommitteeId, model);
                return RedirectToAction("GetAllCommittee");
            }
            return View();
        }

        public IActionResult DeleteCommittee(int id)
        {
            CmtRepository.DeleteCommittee(id);
            return RedirectToAction("GetAllCommittee");
        }

        ////  Event ////

        [HttpGet]
        public IActionResult AddEvent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEvent(EventModel model)
        {
            if (ModelState.IsValid)
            {
                int id = EvntRepository.AddEvent(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.success = "Data Added";
                }
            }
            return View();
        }

        public IActionResult GetAllCss()
        {
            var result = CssRepository.GetAllCssVariables();
            return View(result);
        }

        [HttpGet]
        public IActionResult EditCss(int id)
        {
            var evnt = CssRepository.GetCssVariables(id);
            return View(evnt);
        }

        [HttpPost]
        public IActionResult EditCss(CssVariableModel model)
        {
            if (ModelState.IsValid)
            {
                CssRepository.UpdateCssVariables(model.VarId, model);
                return RedirectToAction("GetAllCss");
            }
            return View();
        }

        public IActionResult GetAllEvent()
        {
            var result = EvntRepository.GetAllEvent();
            return View(result);
        }

        public IActionResult EventDetails(int id)
        {
            var evnt = EvntRepository.GetEvent(id);
            return View(evnt);
        }

        [HttpGet]
        public IActionResult EditEvent(int id)
        {
            var evnt = EvntRepository.GetEvent(id);
            return View(evnt);
        }

        [HttpPost]
        public IActionResult EditEvent(EventModel model)
        {
            if (ModelState.IsValid)
            {
                EvntRepository.UpdateEvent(model.EventId, model);
                return RedirectToAction("GetAllEvent");
            }
            return View();
        }

        public IActionResult DeleteEvent(int id)
        {
            EvntRepository.DeleteEvent(id);
            return RedirectToAction("GetAllEvent");
        }

        //public IActionResult GetAllContact()
        //{
        //    var result = contactRepository.GetAllContact();
        //    if (result != null)
        //    {
        //        return View(result);
        //    }
        //    return View();
        //}

        //public IActionResult ContactDetails(int id)
        //{
        //    var result = contactRepository.GetContact(id);
        //    return View(result);
        //}

        //public IActionResult ReplyMessage(string email)
        //{           
        //    ViewBag.Email = email;
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult ReplyMessage(EmailReplyModel model, int id)
        //{
        //    //Read SMTP settings from AppSettings.json.
        //    string host = this.Configuration.GetValue<string>("Smtp:Server");
        //    int port = this.Configuration.GetValue<int>("Smtp:Port");
        //    string fromAddress = this.Configuration.GetValue<string>("Smtp:FromAddress");
        //    string userName = this.Configuration.GetValue<string>("Smtp:UserName");
        //    string password = this.Configuration.GetValue<string>("Smtp:Password");

        //    using (MailMessage mm = new MailMessage(fromAddress, model.Email))
        //    {
        //        mm.Subject = model.Subject;
        //        mm.Body = "<br /><br />Email: " + model.Email + "<br />" + model.Body;
        //        mm.IsBodyHtml = true;

        //        using (SmtpClient smtp = new SmtpClient())
        //        {
        //            smtp.Host = host;
        //            smtp.EnableSsl = true;
        //            NetworkCredential NetworkCred = new NetworkCredential(userName, password);
        //            //smtp.UseDefaultCredentials = true;
        //            smtp.UseDefaultCredentials = false;
        //            smtp.Credentials = NetworkCred;
        //            smtp.Port = port;
        //            smtp.Send(mm);                   
        //            contactRepository.UpdateReplyStatus(id);
        //            ViewBag.Message = "Email sent sucessfully.";
        //        }
        //    }

        //    return View();
        //}
    }
}

AustPIC_official-main/AustPICWeb/Controllers/BlogController.cs
using AustPIC.Models;
using AustPIC.Models.ViewModels;
using AustPICWeb.Repositories.Blog;
using AustPICWeb.Repositories.CssVariable;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AustPICWeb.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogRepository _blogRepository;
        private readonly ICssRepository _cssRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(IBlogRepository blogRepository, ICssRepository cssRepository, IWebHostEnvironment webHostEnvironment)
        {
            _blogRepository = blogRepository;
            _cssRepository = cssRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index(string category, string date)
        {
            //var blogTop2 = await _blogRepository.GetTop2BlogList();
            //var topblog = await _blogRepository.GetTopBlog();
            var categoryList = await _blogRepository.GetBlogCategoryList();
            var dateList = await _blogRepository.GetBlogDateList();
            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;

            if (category != null)
            {
                ViewBag.Category = category;
                var blogList = await _blogRepository.GetBlogListByCategory(category);
                var model = new BlogViewModel { blogList = blogList, category = categoryList, date = dateList };

                return View(model);
            }
            else if (date != null)
            {
                ViewBag.Date = date;
                var blogList = await _blogRepository.GetBlogListByDate(date);
                var model = new BlogViewModel { blogList = blogList, category = categoryList, date = dateList };

                return View(model);
            }
            else
            {
                var blogList = await _blogRepository.GetBlogList();
                var model = new BlogViewModel { blogList = blogList, category = categoryList, date = dateList };

                return View(model);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            var categoryList = await _blogRepository.GetBlogCategoryList();
            var dateList = await _blogRepository.GetBlogDateList();
            ViewBag.Category = categoryList;
            ViewBag.Date = dateList;
            var detail = await _blogRepository.GetBlogDetail(id);

            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;
            return View(detail);
        }

        public async Task<IActionResult> CreateBlog()
        {
            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> CreateBlog(BlogModel blog, IFormFile img)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (img != null && img.Length > 0)
        //        {
        //            string folder = "blogs/image/";
        //            folder += Guid.NewGuid().ToString() + "_" + img.FileName;

        //            blog.BlogImg = folder;

        //            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

        //            await img.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
        //        }

        //        await _blogRepository.AddBlogDetail(blog);
        //        return Ok();
        //    }

        //    var cssVariables = await _cssRepository.GetCssVariablesList();
        //    ViewBag.CssVariables = cssVariables;
        //    return View(blog);
        //} 

        [HttpPost]
        public async Task<IActionResult> CreateBlog(BlogModel blog)
        {
            if (ModelState.IsValid)
            {
                if (blog.BlogImgFile != null && blog.BlogImgFile.Length > 0)
                {
                    string folder = "blogs/image/";
                    folder += Guid.NewGuid().ToString() + "_" + blog.BlogImgFile.FileName;

                    blog.BlogImg = folder;

                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await blog.BlogImgFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }

                try
                {
                    if(blog.BlogClass != "negative")
                    {
                        await _blogRepository.AddBlogDetail(blog);
                    }
                    return Ok();
                }
                catch
                (Exception ex)
                {
                    return StatusCode(500, "error");
                }

            }

            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;
            return View(blog);
        }


    }
}

AustPIC_official-main/AustPICWeb/Controllers/NewsController.cs
using AustPICWeb.Repositories.Contest;
using AustPICWeb.Repositories.CssVariable;
using Microsoft.AspNetCore.Mvc;

namespace AustPICWeb.Controllers
{
    public class NewsController : Controller
    {
        private readonly IContestRepository _contestRepository;
        private readonly ICssRepository _cssRepository;

        public NewsController(IContestRepository contestRepository, ICssRepository cssRepository)
        {
            _contestRepository = contestRepository;
            _cssRepository = cssRepository;
        }

        public async Task<IActionResult> Index()
        {
            var contests = await _contestRepository.GetContestList();
            var cssVariables = await _cssRepository.GetCssVariablesList();
            ViewBag.CssVariables = cssVariables;
            return View(contests);
        }

    }
}

AustPIC_official-main/AustPICWeb/Views/Shared/_FooterPartial.cshtml
<footer id="footer">

    <div class="footer-newsletter">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h4>Join Our Newsletter</h4>
                    @*<p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>*@
                    <form method="post" data-ajax="true" data-ajax-complete="onCompleteNewsletter" data-ajax-success="onSuccessNewsletter" data-ajax-failure="onFailureNewsletter" data-ajax-loading="#spinner" data-ajax-url="@Url.Action("Index", "Newsletter")">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
                        <input type="submit" value="Subscribe">
                    </form>
                    <div class="d-flex justify-content-center my-4">
                        <div class="spinner-border" role="status" id="spinner" style="display: none;">
                        <span class="visually-hidden">Loading...</span>
                   </div>
                 </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>AUSTPIC</h3>
                    <p>
                        141 & 142, Love Road <br>
                        Tejgaon Industrial Area, Dhaka-1208<br>
                        Bangladesh <br><br>
                        <strong>Phone:</strong> (8802) 8870422<br>
                        <strong>Email:</strong> info@aust.edu<br>
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="" asp-action="Index">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Gallery" asp-action="Index">Gallery</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Participate In</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Contest" asp-action="Index">Contests</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Event" asp-action="Index">Events</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Workshop" asp-action="Index">Workshops</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a asp-controller="Blog" asp-action="Index">Blogs</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Social Networks</h4>
                    @*<p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>*@
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container footer-bottom clearfix">
        <div class="copyright">
            &copy; Copyright <strong><span>AUSTPIC</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="">ASP</a>
        </div>
    </div>

</footer>

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

AustPIC_official-main/AustPICWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AustPIC</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="vendor/aos/aos.css" rel="stylesheet">
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="lib/toastr.js/toastr.min.css" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    @*@RenderSection("Style", required: false)*@

@*    <style>
        :root {
            --a-hover-color: #73c5eb;
            --navbar-scroll-color-rgb: 40, 58, 90;
            --hero-bg-color: #37517e;
            --hero-button-bg-color: #47b2e4;
            --hero-button-bg-color-hover: #209dd8;
            --hero-bottom-divider-bg-color: #f3f5fa;
            --achievements-bg-img: url("../img/formation.jpg");
            --hero-bg-color-rgb: 55, 81, 126;
            --team-divider-color: #cbd6e9;
            --team-social-bg-color: #eff2f8;
            --contact-info-icon-bg-color: #e7f5fb;
            --contact-info-p-color: #6182ba;
            --breadcrumbs-slash-color: #4668a2;
        }
    </style>*@

    <style>
        :root {
        @foreach (var variable in ViewBag.CssVariables)
        {
            @Html.Raw(variable.VarName + ": " + variable.VarValue + ";")
        }
        }
    </style>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <partial name="_NavbarPartial" />
    </header>
    <!-- End Header -->
    @*    <div role="main" id="NavbarContainer">
    </div>*@

    <main role="main" class="">
        @RenderBody()
    </main>

    <!-- ======= Footer ======= -->
    <partial name="_FooterPartial" />
    <!-- End Footer -->
    <!-- Vendor JS Files -->
    <script src="vendor/aos/aos.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/glightbox/js/glightbox.min.js"></script>
    <script src="vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="vendor/swiper/swiper-bundle.min.js"></script>
    <script src="vendor/waypoints/noframework.waypoints.js"></script>
@*    <script src="vendor/php-email-form/validate.js"></script>*@

    <!-- Template Main JS File -->
    <script src="js/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*    <script>
    $(document).ready(function () {
    alert("Doc is ready");
    });
    </script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AustPIC_official-main/AustPICWeb/Views/Shared/_LayoutInner.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AustPIC</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>

    <style>
        :root {
        @foreach (var variable in ViewBag.CssVariables)
        {
            @Html.Raw(variable.VarName + ": " + variable.VarValue + ";")
        }
        }
    </style>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-inner-pages">
        <partial name="_NavbarPartial" />
    </header>
    <!-- End Header -->

    <main id="main">
        @RenderBody()
    </main>

    <!-- ======= Footer ======= -->
    <partial name="_FooterPartial" />
    <!-- End Footer -->
    <!-- Vendor JS Files -->
    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/vendor/waypoints/noframework.waypoints.js"></script>
    @*<script src="~/vendor/php-email-form/validate.js"></script>*@

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="//editor.unlayer.com/embed.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/site1.js"></script>
</body>

</html>

AustPIC_official-main/AustPICWeb/Views/Shared/_NavbarPartial.cshtml
@*<style>
    #navbar {
    }
</style>*@


<div class="container d-flex align-items-center">

    <h1 class="logo me-auto"><a>AUSTPIC</a></h1>
    <!-- <a href="index.html" class="logo me-auto"><img src="img/logo.png" alt="" class="img-fluid"></a>-->

    <nav id="navbar" class="navbar">
        <ul>
            <li><a class="nav-link scrollto active" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="dropdown">
                <a href="#"><span>Club Committee</span> <i class="bi bi-chevron-down"></i></a>
                @await Component.InvokeAsync("CommitteeSemester")
            </li>
            <li class="dropdown">
                @*<a href="#" onclick="loadNavBarView('News/Index')"><span>News</span> <i class="bi bi-chevron-down"></i></a>*@
                <a href="#"><span>News</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                    <li><a asp-controller="News" asp-action="Index">Notice</a></li>
                    <li><a asp-controller="Contest" asp-action="Index">Contests</a></li>
                </ul>
            </li>
            <li><a class="nav-link scrollto" asp-controller="Event" asp-action="Index">Events</a></li>
            <li><a class="nav-link scrollto" asp-controller="Workshop" asp-action="Index">Workshops</a></li>
            <li><a class="nav-link scrollto" asp-controller="Blog" asp-action="Index">Blog</a></li>
            <li><a class="nav-link scrollto" asp-controller="Gallery" asp-action="Index">Gallery</a></li>
            <li><a class="nav-link scrollto" asp-controller="About" asp-action="Index">About Us</a></li>
            <li><a class="nav-link scrollto" asp-controller="Contact" asp-action="Index">Contact</a></li>
            <partial name="_LoginPartial" />
            @if (User.IsInRole("Administrator"))
            {
                <li><a class="getstarted scrollto" asp-controller="Admin" asp-action="Index">Admin Panel</a></li>
            }
            @*<li><a class="getstarted scrollto" asp-controller="Home" asp-action="Login">Login/Signup</a></li>*@
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

</div>